package com.dgsocketserver.exception

import com.dgsocketserver.exception.common.CustomException
import com.dgsocketserver.exception.common.GlobalExceptionCode

class InternalServerException: CustomException(GlobalExceptionCode.INTERNAL_SERVER)