package com.dgsocketserver.exception

import com.dgsocketserver.exception.common.CustomException
import com.dgsocketserver.exception.common.GlobalExceptionCode

class InvalidParameterException: CustomException(GlobalExceptionCode.PARAMETER_NOT_VALID)